version: "3"
services:
  perfomance-management-system:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://olusesia:RUybhJuAdw7hLUQE@cluster0.pp5axps.mongodb.net/
